spring:
  application:
    name: bsba
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

momo:
  api:
    base-url: https://test-payment.momo.vn
    path: /v2/gateway/api/create
    partner-code: MOMO
    access-key: F8BBA842ECF85
    secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
    ipn-url: https://prone-distract-monstrous.ngrok-free.dev/api/Wallet/deposit/momo-ipn
    redirect-url: https://google.com
    request-type: captureWallet
    lang: vi
    timeout-seconds: 30
