spring:
  profiles:
    default: dev
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:./bsba_be/.env[.properties]
      - optional:file:../.env[.properties]
  application:
    name: bsba
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${spring.mail.host:smtp.gmail.com}
    port: ${spring.mail.port:587}
    username: ${spring.mail.username:}
    password: ${spring.mail.password:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24 hours

google:
  client:
    id: ${GOOGLE_CLIENT_ID:your_client_id.apps.googleusercontent.com}

momo:
  api:
    base-url: https://test-payment.momo.vn
    path: /v2/gateway/api/create
    partner-code: MOMO
    access-key: F8BBA842ECF85
    secret-key: K951B6PE1waDMi640xX08PD3vg6EkVlz
    ipn-url: https://prone-distract-monstrous.ngrok-free.dev/api/Wallet/deposit/momo-ipn
    redirect-url: https://google.com
    request-type: captureWallet
    lang: vi
    timeout-seconds: 30

zalopay:
  app-id: ${ZALOPAY_APP_ID:}
  key1: ${ZALOPAY_KEY1:}
  key2: ${ZALOPAY_KEY2:}
  create-order-url: ${ZALOPAY_CREATE_ORDER_URL:https://sb-openapi.zalopay.vn/v2/create}
  query-order-url: ${ZALOPAY_QUERY_ORDER_URL:https://sb-openapi.zalopay.vn/v2/query}
  callback-url: ${ZALOPAY_CALLBACK_URL:}
